version: "3.7"

services:
  app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - node-network
  nginx:
    container_name: node-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - node-network
networks:
  node-network:
    driver: bridge
